In [2]:
import pandas as pd

mambo = pd.read_csv("base/mambo.csv")
marche = pd.read_csv("base/marche.csv")
base_cafe = pd.read_excel("base/base_cafe.xlsx", sheet_name="dados")

In [4]:
mambo.head()

,SKU,Titulo,Fabricante,Categoria,Disponibilidade,Preco,Preço Oferta,URL
0,2532,Café Torrado e Moído Superior Aviação 500g,Aviação,Mercearia,Disponivel,54.98,54.98,https://www.mambo.com.br/cafe-superior-moido-a...
1,2533,Café Torrado e Moído 252 Graus a Vácuo Pilão 500g,Pilão,Mercearia,Disponivel,43.49,43.49,https://www.mambo.com.br/cafe-torrado-e-moido-...
2,2534,Café Torrado e Moído 252° Graus Abre & Fecha P...,Pilão,Mercearia,Disponivel,43.49,43.49,https://www.mambo.com.br/cafe-torrado-e-moido-...
3,2536,Café Torrado e Moído a Vácuo Tradicional 3 Cor...,3 Corações,Mercearia,Disponivel,27.99,27.99,https://www.mambo.com.br/cafe-torrado-e-moido-...
4,2537,Cápsula de Café Aqtivus 8 Delta 55g com 10 Uni...,Delta Q,Mercearia,Disponivel,28.49,28.49,https://www.mambo.com.br/cafe-aqtivus-8-delta-...

In [5]:
marche.head()

,SKU,Titulo,Fabricante,Categoria,Disponibilidade,Preco,Preço Oferta,URL
0,20026827,Cápsulas de Café Illy Descafeinado 18 Unidades,Illy,Café,Disponivel,71.29,71.29,https://marche.com.br/collections/mercearia/pr...
1,20060012,Café L'or Torrado e Moído Equilibrado Torras G...,Lor,Café,Disponivel,30.49,30.49,https://marche.com.br/collections/mercearia/pr...
2,20055865,Cápsula de Café ORFEU Intenso Dolce Gusto 90g,Orfeu,Café,Disponivel,32.49,32.49,https://marche.com.br/collections/mercearia/pr...
3,20031287,Café em Cápsula L'or Torrado e Moído Lungo Esp...,Lor,Café,Disponivel,30.99,30.99,https://marche.com.br/collections/mercearia/pr...
4,20063958,Cápsulas de Café Baobá Especial Intenso 10 Uni...,Baobá,Café,Disponivel,35.69,35.69,https://marche.com.br/collections/mercearia/pr...

In [6]:
base_cafe.head()

,Código,Descrição,Departamento,Categoria/Setor,Marca,Famlíia,Código do Fabricante,Código de Barras,SKU Monitorado,Website Monitorado,URL Produto Monitorado,Data,Média Preço Normal,Média Preço Oferta,Leituras,Leituras com disponibilidade,URL Monitor,Desvio Média Preço %,Marca Target
0,1038723,Café Torrado e Moído Extraforte Pilão Pacote 500g,Alimentos,Básico da despensa,pa,NaN,NaN,7896089013399,1038723,www.paodeacucar.com,https://www.paodeacucar.com/produto/292186/caf...,2026-03-08,27.49,27.49,22,22,https://monitor.precifica.com.br/index.php/Pro...,28.4,False
1,1038723,Café Torrado e Moído Extraforte Pilão Pacote 500g,Alimentos,Básico da despensa,pa,NaN,NaN,7896089013399,1038723,www.paodeacucar.com,https://www.paodeacucar.com/produto/292186/caf...,2026-03-07,27.49,27.49,24,24,https://monitor.precifica.com.br/index.php/Pro...,28.4,False
2,1038723,Café Torrado e Moído Extraforte Pilão Pacote 500g,Alimentos,Básico da despensa,pa,NaN,NaN,7896089013399,1038723,www.paodeacucar.com,https://www.paodeacucar.com/produto/292186/caf...,2026-03-06,27.49,27.49,24,17,https://monitor.precifica.com.br/index.php/Pro...,28.4,False
3,183567,Café Torrado e Moído Extraforte 3 Corações Pac...,Alimentos,Básico da despensa,pa,NaN,NaN,7896005801529,183567,www.paodeacucar.com,https://www.paodeacucar.com/produto/57156/cafe...,2026-03-08,27.99,27.99,22,22,https://monitor.precifica.com.br/index.php/Pro...,NaN,False
4,183567,Café Torrado e Moído Extraforte 3 Corações Pac...,Alimentos,Básico da despensa,pa,NaN,NaN,7896005801529,183567,www.paodeacucar.com,https://www.paodeacucar.com/produto/57156/cafe...,2026-03-07,27.99,27.99,24,23,https://monitor.precifica.com.br/index.php/Pro...,NaN,False

In [3]:
mambo.shape
marche.shape
base_cafe.shape

(1047, 19)

In [7]:
base_total = pd.concat([base_cafe, mambo, marche], ignore_index=True)

In [8]:
base_total.head()

,Código,Descrição,Departamento,Categoria/Setor,Marca,Famlíia,Código do Fabricante,Código de Barras,SKU Monitorado,Website Monitorado,...,Desvio Média Preço %,Marca Target,SKU,Titulo,Fabricante,Categoria,Disponibilidade,Preco,Preço Oferta,URL
0,1038723.0,Café Torrado e Moído Extraforte Pilão Pacote 500g,Alimentos,Básico da despensa,pa,NaN,NaN,7.896089e+12,1038723.0,www.paodeacucar.com,...,28.4,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1038723.0,Café Torrado e Moído Extraforte Pilão Pacote 500g,Alimentos,Básico da despensa,pa,NaN,NaN,7.896089e+12,1038723.0,www.paodeacucar.com,...,28.4,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1038723.0,Café Torrado e Moído Extraforte Pilão Pacote 500g,Alimentos,Básico da despensa,pa,NaN,NaN,7.896089e+12,1038723.0,www.paodeacucar.com,...,28.4,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,183567.0,Café Torrado e Moído Extraforte 3 Corações Pac...,Alimentos,Básico da despensa,pa,NaN,NaN,7.896006e+12,183567.0,www.paodeacucar.com,...,NaN,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,183567.0,Café Torrado e Moído Extraforte 3 Corações Pac...,Alimentos,Básico da despensa,pa,NaN,NaN,7.896006e+12,183567.0,www.paodeacucar.com,...,NaN,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN